# Generated by Django 5.1.6 on 2025-03-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qs2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuenumber',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='queuenumber',
            unique_together={('number', 'created_at')},
        ),
    ]
